default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: (4sswor)
  timeout: 5000

development:
  <<: *default
  database: nexoos
test:
  <<: *default
  databese: nexoos

production:
  <<: *default
database: nexoos
